apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-common-config
data:
  {{- range $key, $val := index .Values .Values.werf.env }}
  {{ $key | snakecase | upper }}: {{ quote $val }} 
  {{- end }}
